### PR TITLE
Remove timestamp and rename export

### PR DESCRIPTION
**Pull request by chrisguttandin**
This PR is intended to implement the changes discussed here: #79.

It can be tested by installing dynamo-converters like this:

```bash
npm i git://github.com/chrisguttandin/dynamo-converters.git#remove-timestamp-and-rename-export-build
```

### CODE REVIEW

**Review by deini — COMMENTED** [review]
Haven't been able to test this yet, but code lgtm. Thanks for doing this 🙇

**Comment by chrisguttandin** [comment]
@deini, no problem I didn't expect you to check it right away. I just thought it would be useful if you could double-check that the changes work for you too before we publish them. Just let me know when you got a moment to verify the update. Many thanks in advance.

**Comment by chrisguttandin** [comment]
Hi @deini, did you meanwhile manage to give these changes a try?

**Comment by deini** [comment]
@chrisguttandin I apologize, thought I had replied. 

This works as expected, we've been using it for a while now. Thanks!

**Comment by chrisguttandin** [comment]
No problem, the same happened to me. I was using the branch with the build and almost forgot about this PR. :-)

I just published v6 which contains the changes. I'll wait a little longer before I delete the branch with the build to avoid any hiccups on your end.

**Comment by deini** [comment]
@chrisguttandin Bumped to v6, thanks for your consideration. 🙇

**Comment by chrisguttandin** [comment]
Okay, in that case I will kill the branch right away. 🧹

**Pull request merged**
